#!/usr/bin/env python
"""recognize_face.py

Live face recognition using OpenCV LBPH recognizer.
Assumes data/people/<name>/*.png images exist (generated by register_face.py).

Usage:
    python recognize_face.py --source 0
"""

import argparse
import sys
from pathlib import Path
import cv2
import numpy as np

from face_follower import load_detector


def load_training_data(base_dir: Path):
    images, labels, label_map = [], [], {}
    label_id = 0
    for person_dir in base_dir.iterdir():
        if not person_dir.is_dir():
            continue
        label_map[label_id] = person_dir.name
        for img_path in person_dir.glob("*.png"):
            img = cv2.imread(str(img_path), cv2.IMREAD_GRAYSCALE)
            images.append(img)
            labels.append(label_id)
        label_id += 1
    return images, np.array(labels), label_map


def main():
    parser = argparse.ArgumentParser(description="Real-time face recognition")
    parser.add_argument("--source", type=int, default=0, help="Camera index")
    args = parser.parse_args()

    data_dir = Path("data/people")
    if not data_dir.exists():
        sys.exit("No registered faces found. Run register_face.py first.")

    images, labels, label_map = load_training_data(data_dir)
    recognizer = cv2.face.LBPHFaceRecognizer_create()
    recognizer.train(images, labels)

    detector = load_detector()
    cap = cv2.VideoCapture(args.source)
    if not cap.isOpened():
        sys.exit("Cannot open camera")

    while True:
        ok, frame = cap.read()
        if not ok:
            continue
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        faces = detector.detectMultiScale(gray, 1.1, 5, minSize=(80, 80))
        for x, y, w, h in faces:
            roi = gray[y : y + h, x : x + w]
            roi = cv2.resize(roi, (200, 200))
            label_id, confidence = recognizer.predict(roi)
            name = label_map.get(label_id, "Unknown")
            cv2.putText(
                frame,
                f"{name} {confidence:.0f}",
                (x, y - 10),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.8,
                (0, 255, 0),
                2,
            )
            cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)
        cv2.imshow("Recognize", frame)
        if cv2.waitKey(1) & 0xFF == 27:
            break

    cap.release()
    cv2.destroyAllWindows()


if __name__ == "__main__":
    main()
